name: movies
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.3.1
  youtube_player_flutter: ^9.1.1
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  provider: ^6.1.2
  animations: ^2.0.11
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  avatar_glow: ^2.0.2
  intl: ^0.19.0
  youtube_player_iframe: ^4.0.4
  geolocator: ^10.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/genres/
    - assets/images/language/
    # Ensure correct spacing and file exists
